variable "project_name" {}
variable "region" {}
variable "vpc_cidr" {}
variable "public_subnet_az1_cidr" {}
variable "public_subnet_az2_cidr" {}
variable "private_subnet_app_az1_cidr" {}
variable "private_subnet_app_az2_cidr" {}
variable "private_subnet_data_az1_cidr" {}
variable "private_subnet_data_az2_cidr" {}